### ISSUE TITLE
Host storage 

### ISSUE THREAD

**Issue by vinird** [vinird/ionic-ethereum-tester-app#1]
The app is using local storage, in order to make it works a set of host value is needed.

**Comment by c-macn** [comment]
@vinird Could you give a bit more information about this issue? What values need to be placed in local storage?

**Comment by vinird** [comment]
We need to save only one value (host) in the local store database. And it will be nice to trigger a toast if it was saved successfully.

**Comment by c-macn** [comment]
@vinird thanks I can take a look at this

**Comment by ChrisMcNulty91** [comment]
@vinird I don't have permissions to push a feature branch to create a PR
