### ISSUE TITLE
Event for button

### ISSUE THREAD

**Issue by vinird** [vinird/ionic-ethereum-tester-app#3]
In Start page, we need to trigger an event to save the value of the input. No database interaction is needed.

**Comment by rakeshtinku** [comment]
i would like to help you with this

**Comment by vinird** [comment]
Please go ahead.

**Comment by rakeshtinku** [comment]
i've created a pull request. check that



*[image: facebook]
<https://www.facebook.com/GaianSolutionsIndiaPvtLtd>[image: twitter]
<https://twitter.com/GaiaTelevision>[image: LinkedIn]
<https://www.linkedin.com/company/gaian-solutions>[image: gplus]
<https://plus.google.com/u/0/b/117157936357902725155/117157936357902725155/posts>*
<https://twitter.com/GaiaTelevision>
<https://www.facebook.com/GaianSolutionsIndiaPvtLtd>
<https://www.linkedin.com/company/gaian-solutions>
<https://plus.google.com/u/0/b/117157936357902725155/117157936357902725155/about>


*Rakesh Talarolu *| ST

*rakesh.talarolu@gaiansolutions.com <p.veena@gaiansolutions.com>*  |
<http://www.gaiansolutions.com/>www.gaiansolutions.com

Hyderabad, India
M: +91 9666852996
